# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: IMXD Lab # jekyll-seo-tag > Owners twitter username
author: IMXD Lab # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: IMXD Lab # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/vratidc
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  sass_dir: _sass
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "IMXD Lab" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/imxd-logo-nb.png" # Site logo, also used in jekyll-seo-tag
description: "The IMXD Lab Homepage" # Site description and default description, also used in jekyll-seo-tag
url: "https://vratidc.github.io/imxd-test" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/vratidc/imxd-test"
email: "vratidc@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  192: '/assets/logos/imxd-favicon.png'

# 9. Site navigation
navigation_header:
- title: Works
  url: /works
- title: People
  url: /people
- title: About
  url: /about
- title: Contact
  url: /contact

navigation_footer:
- title: Contact Us
  url: https://vratidc.github.io
- title: IDC School of Design
  url: https://vratidc.github.io
- title: IIT Bombay
  url: https://vratidc.github.io

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/vratidc
  
sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Email: true
